version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.3.2
    ports:
      - '9200:9200'
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      #jvm max 8g min 2g
      ES_JAVA_OPTS: "-Xmx8g -Xms2g"
      discovery.type: single-node
  kibana:
    image: kibana:8.3.2
    ports:
      - '5601:5601'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:8.3.2
    ports:
      - '514:514/udp'
    volumes:
      #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch

