version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.3.2
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
  kibana:
    image: kibana:8.3.2
    ports:
      -'5601:5601'
    depends_on:
      - elasticsearch