version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.3.2
    env_file: .env
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:$ELASTIC_DIR/config/elasticsearch.yml:ro
      - elasticsearch:$ELASTIC_DIR/data
      - ./setup/kEy:$ELASTIC_DIR/kEy:rw
      - ./setup/setup.sh:$ELASTIC_DIR/setup.sh:ro
      - ./setup/instances.yml:$ELASTIC_DIR/config/instances.yml:ro
      - ./setup/certs:/tmp/certs
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_SYSTEM_PASSWORD": ${LOGSTASH_SYSTEM_PASSWORD:-}
      discovery.type: single-node

  kibana:
    image: kibana:8.3.2
    env_file: .env
    volumes:
      - ./kibana/config/kibana.yml:$KIBANA_DIR/config/kibana.yml:ro
      - ./setup/certs:/tmp/certs
      - ./setup/setup.sh:$KIBANA_DIR/setup.sh:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  logstash:
    image: logstash:8.3.2
    env_file: .env
    volumes:
      - ./logstash/config/logstash.yml:$LOGSTASH_DIR/config/logstash.yml:ro
      - ./logstash/pipeline/cisco.conf:$LOGSTASH_DIR/pipeline/logstash.conf:ro
      - ./setup/certs:/tmp/certs
      - ./setup/setup.sh:$LOGSTASH_DIR/setup.sh:ro
    ports:
      - "514:514/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch


volumes:
  elasticsearch:

networks:
  elk:
    driver: bridge