version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.3.2
    ports:
      - '9200:9200'
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      #jvm max 8g min 2g
      ES_JAVA_OPTS: "-Xmx8g -Xms2g"
      discovery.type: single-node
  kibana:
    image: kibana:8.3.2
    ports:
      - '5601:5601'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch