version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.3.2
    env_file: .env
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_SYSTEM_PASSWORD": ${LOGSTASH_SYSTEM_PASSWORD:-}
      discovery.type: single-node
  
  kibana:
    image: kibana:8.3.2
    env_file: .env
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  logstash:
    image: logstash:8.3.2
    env_file: .env
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline/cisco.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "514:514/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch


volumes:
  elasticsearch:

networks:
  elk:
    driver: bridge