http.host: "0.0.0.0"
##turn http to https after generating certs and copy it to config directory
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

## X-Pack security credentials
xpack.monitoring.enabled: true

##activate only when enable security in elasticsearch
# xpack.monitoring.elasticsearch.username: logstash_system
# xpack.monitoring.elasticsearch.password: "${LOGSTASH_SYSTEM_PASSWORD}"

##activate only after generating certs and copy it to config directory
#xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/certs/ca.crt


##CHECK PIPELINES AFTER ADDING SECURITY!!!